spring.application.name=bookapplication
server.port=9090
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=com.mysqp.cj.jdbc.Driver
spring.datasource.url=
jdbc:mysql://localhost:3306/bookdb
spring.datasource.username=root
spring.datasource.password=ROCKY1309
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MYSQL8Dialect
